name: Run JAR and Deploy HTML

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up Java
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3. Run the JAR to generate teams.html
      - name: Run JAR
        run: java -cp ScoutingParser-1.0-SNAPSHOT.jar com.strubium.gasstation.Main

      # 4. Ensure the output folder exists for deployment
      - name: Prepare deployment folder
        run: |
          mkdir -p frc
          mv teams.html frc/

      # 5. Deploy HTML to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frc
